version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.1.0
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: 
          command: cd flutter_client && flutter pub get
          background: false
      - run:
          command: cd flutter_client && flutter analyze
          
            

workflows:
  build:
    jobs:
      - build